/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/audiquattroquentin.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0017_001_Mesh_0017_023.geometry}
        material={materials["18___Rubber"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0017_002_Mesh_0017_024.geometry}
        material={materials["18___Rubber"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0017_003_Mesh_0017_025.geometry}
        material={materials["18___Rubber"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0017_022.geometry}
        material={materials["18___Rubber"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0095_003.geometry}
        material={materials.Tex_0031_0_dds_001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0096_002.geometry}
        material={materials.Tex_0001_0_dds_008}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0098_002.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0145_003.geometry}
        material={materials.Tex_0031_0_dds_001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0148_002.geometry}
        material={materials.Tex_0001_0_dds_008}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0149_003.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0152_001.geometry}
        material={materials.Tex_0031_0_dds_001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0194_004.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0249_002.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0293_004.geometry}
        material={materials.Tex_0001_0_dds_008}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0294_004.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0354.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0355.geometry}
        material={materials.Tex_0001_0_dds_008}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0385_006.geometry}
        material={materials.Tex_0189_0_dds}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0386_010.geometry}
        material={materials.Tex_0189_0_dds}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0413_001.geometry}
        material={materials["16___Matte_Plastic"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0434_003.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0447_001.geometry}
        material={materials.Tex_1476_0_dds}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0450_002.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0452.geometry}
        material={materials.Tex_0030_0_dds_003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0456.geometry}
        material={materials.Tex_1478_0_dds_002}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0459_001.geometry}
        material={materials.Tex_0189_0_dds}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0460_001.geometry}
        material={materials.Tex_1524_0_dds}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0462_002.geometry}
        material={materials.Tex_1524_0_dds}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0526_002.geometry}
        material={materials["19___Glass__Thin_wall_"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0527_001.geometry}
        material={materials["19___Glass__Thin_wall_"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0528_001.geometry}
        material={materials["19___Glass__Thin_wall_"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0529_001.geometry}
        material={materials["19___Glass__Thin_wall_"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0531.geometry}
        material={materials["19___Glass__Thin_wall_"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0533_001.geometry}
        material={materials["19___Glass__Thin_wall_"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0534.geometry}
        material={materials["19___Glass__Thin_wall_"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0535.geometry}
        material={materials["19___Glass__Thin_wall_"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0011_001_Mesh_0011_010.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0011_002_Mesh_0011_011.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0011_003_Mesh_0011_012.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0011_009.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0021_001_Mesh_0021_008.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0021_002_Mesh_0021_009.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0021_003_Mesh_0021_010.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0021_007.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0380_004.geometry}
        material={materials["23___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0068_002.geometry}
        material={materials["24___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0384_005.geometry}
        material={materials["24___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0388_005.geometry}
        material={materials["24___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0389_004.geometry}
        material={materials["24___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0403_004.geometry}
        material={materials["24___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0381_006.geometry}
        material={materials["22___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0400_006.geometry}
        material={materials["22___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0401_004.geometry}
        material={materials["22___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0402_005.geometry}
        material={materials["22___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0405_005.geometry}
        material={materials["22___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0406_004.geometry}
        material={materials["22___Default"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/audiquattroquentin.glb");


